### ISSUE TITLE
Make a floating sidebar TOC

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#10]
https://wiki.php.net/rfc/combined-comparison-operator puts the TOC in a sidebar. That's kind of nice. It would be nicer if it floated (position: fixed basically). And maybe highlighted the section you were in.

I think Ecmarkup documents should be able to have this. Probably makes the most sense for smaller proposals but maybe it'd scale to the larger spec.

**Comment by bterlson** [comment]
I note that the linked example is no longer floating... wonder if they decided it was a bad idea? I'm not sure how...

**Comment by bterlson** [comment]
In as of beta5. Try it out, let me know :)
