### ISSUE TITLE
Translate spaces into &nbsp; between ?/! and an abstract op call

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#102]
It looks really sad when they split over lines, and inserting the nbsps myself would be really annoying.

**Comment by bterlson** [comment]
You could also use the code point directly (eg. the ns digraph in vim).

I can probably hack this with a regexp.

**Comment by domenic** [comment]
I figured since you're autolinking already you should be able to back up a bit and if the preceding two characters are "? " or "! " replace them appropriately.

**Comment by bterlson** [comment]
I am autolinking with a giant regexp (ie. not doing a manual scan/parse). I could update the regexp to look for an optional preceding `? ` or `! ` on aoid auto-links I suppose, although this regexp is already the biggest hitter now in terms of perf. That said, you're probably right that doing it as part of the auto-linking regexp will likely be most efficient.
