### ISSUE TITLE
Add a special type of emu-note for spec reviews

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#106]
In writing specs that are destined to eventually land in 262, I run in to two types of notes:
- Normal notes that we anticipate also going into 262
- Notes that are specifically about the spec patch I'm writing.

Currently I'm making do by adding something like "SPEC REVIEWER NOTE:" before the last type. But it would be good to get first-class support, maybe with slightly different styling. (Omit the "NOTE n" thingy? Italics?)

The problem is what to call them. "Meta notes"? "Note to reviewers"? I dunno.

**Comment by bterlson** [comment]
Will be in the next release (committed as f58cbab).
