### ISSUE TITLE
Support [is="emu-alg"], etc.

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#11]
Seems like a good idea in general, and in particular I'd find it a useful workaround for integrating with Bikeshed which recognizes `<pre is="emu-alg">` as "do not touch this" but does not recognize `<emu-alg>` as such.

**Comment by domenic** [comment]
Hmm the resulting styles in the stylesheet are pretty horrid though, you have to end up resetting all the `<pre>` stuff. Maybe I'll work around this another way.

**Comment by bterlson** [comment]
Curious if you were able to work around this in some way?

**Comment by domenic** [comment]
Yeah, I author as pre but convert to emu-alg before passing to ecmarkup. Probably can be closed.
