### ISSUE TITLE
Emit JS/CSS by default including link/script tags

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#111]
The defaults should be flipped. ecmarkup.js and ecmarkup.css should be created in the same directory as the output HTML, with the --js and --css options used to override the location (or remove them I guess; maybe that needs a new option). Then https://github.com/bterlson/ecmarkup/issues/54 should be implemented so the link and script tags get included automatically.

Alternately maybe CSS and JS should be inlined by default. If everyone's getting their own copy, it's not clear there's any benefit in requiring a network round trip for them anyway.

**Comment by bterlson** [comment]
Done in 3.8.
