### ISSUE TITLE
`?` for `_opt` doesn't always work (and is undocumented)

### ISSUE THREAD

**Issue by bakkot** [bterlson/ecmarkup#122]
For example, in ECMA-262, `FunctionExpressions` have `?` after `BindingIdentifier[~Yield, ~Await]` in their grammar, and this [renders](https://tc39.github.io/ecma262/#sec-function-definitions) as a subscript `opt`.

But the same `?` is included elsewhere in the source of the spec, for example in `IsFunctionDefinition`, and [appears](https://tc39.github.io/ecma262/#sec-function-definitions-static-semantics-isfunctiondefinition) to be ignored during rendering. This makes the spec incomplete, to someone reading it as rendered HTML.

Also the [docs](https://bterlson.github.io/ecmarkup/) don't mention `?` at all.

**Comment by sirisian** [comment]
This seems like a huge problem. I just ran into this. As an example this doesn't work either:

Everything is fine in the HTML and the "<emu-mods><emu-opt>opt</emu-opt></emu-mods>" is there, but from the CSS rule:

emu-production[collapsed] emu-mods {
    display: none;
}

It's hidden. Why? I don't know the spec well enough to understand why the CSS rule exists. For my own uses I'm defining:

emu-production[collapsed] emu-mods {
    display: inline-block !important;
}

That seemingly fixes it. Maybe someone can scan all the instance of emu-mods and determine why the rule was created to hide it?

**Comment by jmdyck** [comment]
> Also the [docs](https://bterlson.github.io/ecmarkup/) don't mention `?` at all.

That's because '?' is part of grammarkdown notation.
