### ISSUE TITLE
Which ecmarkup elements don't support ecmarkdown?

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#14]
The introduction says:
> Ecmarkup offers the following conveniences:
> Ecmarkdown syntax in most elements.

It should probably be more specific.

**Comment by bterlson** [comment]
Every element under emu-clause and emu-alg that isn't pre, code, emu-production, or emu-grammar. Will update the docs.

**Comment by bterlson** [comment]
Readme simply states that emu is allowed in "algorithms and paragraphs" which is essentially true and I think all the guidance most users will need :)
