### ISSUE TITLE
suppress auto-linking

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#158]
Sometimes we don't want ecmarkup to auto-link a word. For example, see https://github.com/tc39/ecma262/issues/1730 and https://github.com/tc39/ecma262/pull/1731.

It would be nice if ecmarkup would:
- suppress auto-linking within the `<div id=metadata-block>` element; and/or
- allow the document to spot-disable auto-linking via some markup (e.g.: `<span class="do-not-autolink">Mailing List Archives</span>`)

**Comment by bakkot** [comment]
See also https://github.com/tc39/ecma262/issues/1875.
