### ISSUE TITLE
TOC doesn't support ecmarkdown

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#16]
See e.g. https://littledan.github.io/simd.html#simd-extract-lane. TOC contains "5.2 _SIMD_Constructor" but if you click the link it goes to a heading which is nicely italicized.

**Comment by bterlson** [comment]
Fixed in 1.2.0.

However, I believe this is actually an EMD parsing issue - doesn't the spec mean literal underscores? I think EMD is mistakenly considering the underscore in between words as the end of the EMD var syntax...

**Comment by domenic** [comment]
I am pretty sure the intention in that spec is similar to TypedArray, with the italic part being variable.

**Comment by domenic** [comment]
That said, yeah, maybe the whole _SIMDConstructor_ word should be variable. Existing such variations aren't intra-word.
