### ISSUE TITLE
Underscores cannot be escaped to avoid emphasis formatting

### ISSUE THREAD

**Issue by rwaldron** [bterlson/ecmarkup#20]
ES2015 & Intl 2015 follow a naming convention for Well-Known Intrinsics that involves using an underscore, for example: 

- `Array.prototype.values` => %ArrayProto\_values%
- `Date.now` => %Date\_now% 

Currently ecmarkup ignores an escape and renders text that follows with emphasis

**Comment by bterlson** [comment]
This is tracked in https://github.com/domenic/ecmarkdown/issues/14.
