### ISSUE TITLE
Ecma copyright element

### ISSUE THREAD

**Issue by rwaldron** [bterlson/ecmarkup#21]
```html
<emu-copyright>2015</emu-copyright>
```

Would add the following to a specification document: 

```
Ecma International
Rue du Rhone 114
CH-1204 Geneva
Tel: +41 22 849 6000
Fax: +41 22 849 6001
Web: http://www.ecma-international.org
COPYRIGHT NOTICE

© 2015 Ecma International

This document may be copied, published and distributed to others, and certain derivative works of it may be prepared, copied, published, and distributed, in whole or in part, provided that the above copyright notice and this Copyright License and Disclaimer are included on all such copies and derivative works. The only derivative works that are permissible under this Copyright License and Disclaimer are:

(i)	works which incorporate all or portion of this document for the purpose of providing commentary or explanation (such as an annotated version of the document),

(ii)	works which incorporate all or portion of this document for the purpose of incorporating features that provide accessibility,

(iii)	translations of this document into languages other than English and into different formats and

(iv)	works by making use of this specification in standard conformant products by implementing (e.g. by copy and paste wholly or partly) the functionality therein.

However, the content of this document itself may not be modified in any way, including by removing the copyright notice or references to Ecma International, except as required to translate it into languages other than English or into a different format.

The official version of an Ecma International document is the English language version on the Ecma International website. In the event of discrepancies between a translated version and the official version, the official version shall govern.

The limited permissions granted above are perpetual and will not be revoked by Ecma International or its successors or assigns.

This document and the information contained herein is provided on an "AS IS" basis and ECMA INTERNATIONAL DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION HEREIN WILL NOT INFRINGE ANY OWNERSHIP RIGHTS OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE."

Software License

All Software contained in this document ("Software)" is protected by copyright and is being made available under the "BSD License", included below. This Software may be subject to third party rights (rights from parties other than Ecma International), including patent rights, and no licenses under such third party rights are granted under this license even if the third party concerned is a member of Ecma International. SEE THE ECMA CODE OF CONDUCT IN PATENT MATTERS AVAILABLE AT http://www.ecma-international.org/memento/codeofconduct.htm FOR INFORMATION REGARDING THE LICENSING OF PATENT CLAIMS THAT ARE REQUIRED TO IMPLEMENT ECMA INTERNATIONAL STANDARDS*.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the authors nor Ecma International may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE ECMA INTERNATIONAL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ECMA INTERNATIONAL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by domenic** [comment]
Any reason for the 2015? Why not just add this to every EMU document, with the current year generated?

**Comment by domenic** [comment]
If you only wanted this on final specs or something you could do a mode switch like `<html emu-official>` or `<html emu-final-spec>` or something.

**Comment by rwaldron** [comment]
> Any reason for the 2015? Why not just add this to every EMU document, with the current year generated?

I used "2015" for illustration only, it could be "2016" or "1977" and the copyright would be rendered for that year. 

> a mode switch like `<html emu-official>` or `<html emu-final-spec>`

Something like this might also work well. Here's the use case that prompted my filing this issue: drafts of specifications that are already an official standard need to have a copyright. This is necessary for me to migrate Ecma-402. What do you think?

**Comment by domenic** [comment]
> I used "2015" for illustration only, it could be "2016" or "1977" and the copyright would be rendered for that year. 

Yes, I got that. I am asking whether there's ever a use case for compiling a document with a copyright date that is not the current year at time of document creation.

**Comment by domenic** [comment]
Sorry for multi-message spam.

> Here's the use case that prompted my filing this issue: drafts of specifications that are already an official standard need to have a copyright. This is necessary for me to migrate Ecma-402. What do you think?

I'm excited! It'll be really good to get a smaller spec as a test case before trying it on the mega-spec.

This kind of stuff reminds me of the kind of extra facilities that e.g. [Bikeshed](https://github.com/tabatkins/bikeshed) has. For example:

- https://github.com/tabatkins/bikeshed/blob/master/docs/boilerplate.md
- https://github.com/tabatkins/bikeshed/blob/master/docs/metadata.md

etc. The larger question is really to what extent Ecmarkup might need to adopt all those features. Should it maybe try integrating with Bikeshed? Should it try to acquire extra features like that? How many features are needed---maybe by focusing on ES and related specs, it can stay smaller? I'm not sure yet.

In general I would tend toward adding one-off affordances, exactly like you're proposing in this thread. I imagine only a few more of these sorts of things will be needed to get a full 402 reproduction, which if I'm right, would be a good sign :)

**Comment by rwaldron** [comment]
> In general I would tend toward adding one-off affordances, exactly like you're proposing in this thread. I imagine only a few more of these sorts of things will be needed to get a full 402 reproduction, which if I'm right, would be a good sign :)

Well, so far so good, but I've only gotten through the first few sections ;)

There is no rush at all on this.

**Comment by bterlson** [comment]
I think we should use a similar convention to bikeshed and have a metadata block. I do not propose integrating with bikeshed for the reason that there is presently duplication on a number of things (toc generation) and I think it would be better at least for agility's sake to handle our own metadata. However, by using the same `<pre class="metadata">` and using the same keys when they mean semantically the same thing I believe we can still support emu+bikeshed scenarios.

So, I propose supporting the following metadata:

* Title (aligns with Bikeshed)
* Stage (0-4 or "Final")
* Champion
* Reviewers
* Repository (aligns with Bikeshed)

Stage 0 will not include the copyright boilerplate. Stage 1+ will insert the copyright boilerplate with the current year.

Could consider renaming Champion/Reviewers to editor and Stage to Level to align more closely with bikeshet but I think a deviation is warranted in order to use standard terms.

Seem reasonable?

**Comment by bterlson** [comment]
(Specifically looking to @Domenic to weigh in here from the bikeshed-user perspective)

**Comment by domenic** [comment]
I don't think alignment with Bikeshed is going to be worth it. The models are different; the Python parser for that [infotree](https://github.com/tabatkins/bikeshed/blob/master/docs/infotree.md) format would have to be emulated (presumably incompletely); and I'm not really sure there's an argument for parsing something as both a Bikeshed document and an Emu document.

I think a metadata block is good, and the metadata you proposed seems reasonable (except that "Final" = 4). I would caution against auto-generating a large header as that is generally annoying for readers; instead put stuff like champion and reviewers and copyright at the bottom if possible.

As for the format, I might go with yaml?

**Comment by allenwb** [comment]
A couple of additional points:

Draft Ecma specifications have a different copy notice than final specifications. For drafts, the first section (before the BSD license ) is replaced by:

```
This draft document may be copied and furnished to others, and derivative works that comment on or otherwise explain it or assist in its implementation may be prepared, copied, published, and distributed, in whole or in part, without restriction of any kind, provided that the above copyright notice and this section are included on all such copies and derivative works. However, this document itself may not be modified in any way, including by removing the copyright notice or references to Ecma International, except as needed for the purpose of developing any document or deliverable produced by Ecma International.

This disclaimer is valid only prior to final version of this document. After approval all rights on the standard are reserved by Ecma International.

The limited permissions are granted through the standardization phase and will not be revoked by Ecma International or its successors or assigns during this time.

This document and the information contained herein is provided on an "AS IS" basis and ECMA INTERNATIONAL DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTY THAT THE USE OF THE INFORMATION HEREIN WILL NOT INFRINGE ANY OWNERSHIP RIGHTS OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE."
```
2) Final specification are only issues by the Ecma GA, so the year in the copyright notice should be the year the GA approved that spec.  Drafts should presumably include at least the current year and probably all years that the draft was under development (eg, 2013-2016).

3) Documents that are not drafts of actual specifications (eg, proposals) should be treated as ecma contributions and are licensed under the terms defined for such contributions. That probably should be the default license for the TC39 github project.

**Comment by allenwb** [comment]
You also should added a header block, just like the one for (http://ecma-international.org/ecma-262/6.0/), that explains the relationship between the HTML version and the PDF.

**Comment by bterlson** [comment]
@Domenic Need to differentiate stage 4 from ratified by GA since the copyright boilerplate changes. Maybe ratified instead of final?

> Documents that are not drafts of actual specifications (eg, proposals) should be treated as ecma contributions and are licensed under the terms defined for such contributions.

@allenwb  I'm not entirely clear what those terms are. After executing Exhibit B (where my understanding is for spec text ECMA needs the copyright grant) should the document be copyright ECMA or copyright the authors and how is it licensed?

**Comment by domenic** [comment]
I would assume the GA never ratifies staged proposals; they only ratify the spec as a whole. The spec as a whole needs a different system than the stages; presumably something like "living" vs. "ratified".

**Comment by allenwb** [comment]
@domenic @bterlson According to An "Ecma Standard" is a Ecma "formal document" that has been ratified by the GA.  It always has a standards number such as "ECMA-262-6".  Everything prior to the "final  draft" are "working documents" and are typically assigned TC document numbers, such as  TC39-2015-45. (see https://members.ecma-international.org/get.php?group=TOOLS&file=_sub_Ecma_edit-014.pdf ). Working documents that are draft for an Ecma standard are identified as "Drafts" on their cover page.  (I started the convention of also placing a "draft" watermark on each page).  So, what we have are "standards" and "drafts for standards". Ecma does not have the concept of a "living standard" as only the GA can designate a document as an actual standard. 

Proposals and other documents that have not been physically incorporated into a draft for a standard are also "working documents".  However, as far as Ecma is concerned they don't exist until they have been assigned a document number and archived. We probably need to do this when proposal reach stage 2. 

My understanding is that Ecma hold copyright to its "formal documents" and working documents that are drafts for a standard prepared by an editor. Members retain copyright to their contributions (working documents that are proposals, etc.) but have licensed them (via their membership agreement and the SW contribution form) to Ecma for inclusions in Ecma copyrighted documents.

Ecma has historically put a different (and more restrictive) copyright notice (they called it a "disclaimer") on drafts for standards.  That notice is the one I a quoted in https://github.com/bterlson/ecmarkup/issues/21#issuecomment-129559277 . However, I can't find anything current about that on the Ecma web site.  I'll check with Istvan on that. The basic idea is that drafts should be more restrictive to prevent stuff that doesn't make it into a final standards from being widely incorporated into books, etc.

Ecma has specimen documents in Word (and Framemaker!!) for drafts that, in theory follow all their rules.  We should probably work with Istvan and Patrick to get  official HTML specimen document for draft and final standards.

**Comment by bterlson** [comment]
So interpreting what you're saying, ECMA presently doesn't care how proposals are licensed as long as they don't have a document number. Proposals can therefore be licensed in any way (likely we would want to encourage BSD or, maybe better, apache2). Further, ECMA doesn't have any policies around how proposals should be authored, so we can come up with something reasonable with an eye for easing integration of the proposal into an actual draft.

There is an additional question around whether or when a proposal becomes an officially sanctioned working document. Can't this simply happen when the proposal is incorporated into a draft?

**Comment by allenwb** [comment]
@bterlson Proposals (at least those that make it one the TC39 github project) are Ecma contributions and hence hence has to be made under the licensing terms of the [software copyright policy](http://ecma-international.org/memento/Policies/Ecma_Policy_on_Submission_Inclusion_and_Licensing_of_Software.htm) and the the RF patent policy.

One thing that Ecma is trying to maintain is traceability of where proposal came from and how (and by whom) they have evolved.  Historically, this has been accomplished by using numbered and archived working documents for proposals and revisions (TC39 has not been particularly good at following that process and instead for ES5&6 mostly used the wiki).  

We need to work with Istvan to come up with a low overhead process for proposals that will satisfy  the Ecma archiving and traceability requirements.

**Comment by bterlson** [comment]
Added copyright boilerplate generation for standards, drafts, and proposals in [2.5.0](https://github.com/bterlson/ecmarkup/releases/tag/2.5.0). The copyright boilerplate is added at the very end in an annex. In the future we can think about allowing authors to specify where to fill in the various pieces of boilerplate, but for now the default (or disabling the copyright boilerplate completely) should "Just Work (TM)" for everyone.
