### ISSUE TITLE
Unordered Lists?

### ISSUE THREAD

**Issue by rwaldron** [bterlson/ecmarkup#22]
I feel like I'm missing something obvious, but I find no mention of unordered lists in http://bterlson.github.io/ecmarkup/ 

This fails with the error "Unhandled rejection SyntaxError: Expected "*", "<", "\"", "_", "`", "|", "~", [^\n] or end of input but "\n" found."

```html
<p>
  - The _options_ property localeMatcher in all constructors and supportedLocalesOf methods.
  - The _options_ properties usage and sensitivity in the Collator constructor.
  - The _options_ properties style and currencyDisplay in the NumberFormat constructor.
</p>
```

Attempting to "cheat" or "hack" my way around using `<emu-alg>` fails with the error "Unhandled rejection TypeError: Cannot read property '1' of null"

```html
<emu-alg>
  - The _options_ property localeMatcher in all constructors and supportedLocalesOf methods.
  - The _options_ properties usage and sensitivity in the Collator constructor.
  - The _options_ properties style and currencyDisplay in the NumberFormat constructor.
</emu-alg>
```

The latter definitely makes sense, but the former not-so-much.

I also expect that markdown just isn't allowed like that, which is fine, I just want to verify. I'd love to not have to `<p>` all the time, but any `\n` seems to fail. 

Help?

**Comment by rwaldron** [comment]
I've reviewed the files at https://github.com/tc39/ecmascript-asyncawait/blob/master/spec/ and it seems that a generic list form would be beneficial. 

```html
<emu-list [id="..."]>
  - list item 
  - _another_
  - *bold items*
</emu-list>

<emu-list [id="..."]>
  1. list item 
  1. _another_
  1. *bold items*
</emu-list>
```

**Comment by domenic** [comment]
Yep, Ecmarkdown doesn't support this yet, although we noticed a few instances in the mega-spec when converting. Definitely a necessary feature.

No need for emu-list. You can just use `<ul>`/`<li>` if you need an ID, or use markdown-style no wrapper if you don't.

**Comment by bterlson** [comment]
Opened a tracking issue on emd for this.
