### ISSUE TITLE
cross-reference to something other than a clause

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#24]
As I understand it, <emu-xref> can only refer to a clause in the document. What if one wants to refer to something other than a clause, e.g., a table?

**Comment by bterlson** [comment]
I was thinking href would always refer to a DOM id and emu could have sane defaults for figure, table, and productions. I was considering using the id conventions from es-spec-html where it prefixes section ids with sec-, but I'm not sure this is necessary and it would make xrefs more annoying to write...

**Comment by jmdyck** [comment]
> I was thinking a fragment id href refers to a DOM id

As opposed to what? (How could a fragment id *not* refer to a DOM id?)

> and emu could have sane defaults for figure, table, and productions.

I don't understand what that means. (What thing is defaulting?)

> I was considering using the id conventions from es-spec-html where it prefixes section ids with sec-, but I'm not sure this is necessary and it would make xrefs more annoying to write...

Well, I suppose section ids could drop the 'sec-' prefix as long as every *other* id in the doc 'drove defensively' (e.g., began with a prefix that would never be the start of a section id). But it doesn't seem like a good idea to me.

If xrefs are annoying to write, perhaps the solution is to write fewer of them, rather than to reduce the referenced id by 4 characters.

**Comment by bterlson** [comment]
> As opposed to what? (How could a fragment id not refer to a DOM id?)

Could process it in some way in JS? Not saying it's a good idea.

> I don't understand what that means. (What thing is defaulting?)

The default link text, eg. "3.2" for sections, "Figure 1" for figures, wrap in emu-nt for productions.

> Well, I suppose section ids could drop the 'sec-' prefix as long as every other id in the doc 'drove defensively' (e.g., began with a prefix that would never be the start of a section id). But it doesn't seem like a good idea to me.

Not sure I understand this... not prefixing IDs means all IDs need to be globally unique, which seems like a problem if a section and something else would want the same ID. Not sure how often this would happen in practice though.

If we take id prefixes, do authors need to specify IDs with a prefix or are the prefixes added as part of the build process?.

> perhaps the solution is to write fewer of them,

What does this solution look like? Fewer xrefs is always a good thing.

**Comment by jmdyck** [comment]
> Not sure I understand this... not prefixing IDs means all IDs need to be globally unique, which seems like a problem if a section and something else would want the same ID.

Okay, now I'm confused. You said:
> I was considering using the id conventions from es-spec-html where it prefixes section ids with sec-, but I'm not sure this is necessary

and that sounded to me like you were considering dropping the 'sec-' prefix from section ids, so that's what I was replying to. (Personally, I don't think I'd choose to drop the 'sec-' prefix.)

> If we take id prefixes, do authors need to specify IDs with a prefix or are the prefixes added as part of the build process?

My sense is that it's not a good idea to have the build process alter ids (at either the definition point or reference points). If nothing else, it could result in strange error messages.

>>    perhaps the solution is to write fewer of them,

> What does this solution look like? Fewer xrefs is always a good thing.

Well, for instance, look at ["The String Type" in the ES6 spec](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-string-type). In the second para, there are mentions of String.prototype.normalize and String.prototype.localeCompare, each followed by a cross-ref to the corresponding subclause. But for the HTML version of the spec, the es-spec-html software has changed each of the mentions into a link to the corresponding subclause, thus making the explicit cross-ref redundant. So you can drop those cross-refs, and the HTML won't suffer.

The problem would be if TC39 or ECMA wants the cross-references to work even if you *print* the spec. However:
- Note that in this example, and probably most others, the cross-ref is merely an aid to the reader, and isn't essential to what is being conveyed. So if you took out the cross-refs and then printed the para, it would still have exactly the same normative effect.
- You could possibly have a special build for a print-friendly version of the spec: instead of linkifying certain words/phrases, you could append a cross-ref. But I'm not sure how this would work, since it's unlikely you'd want to insert a cross-ref (into the 'print edition') *everywhere* that the HTML edition has a link -- that'd get cluttered.

**Comment by bterlson** [comment]
If we don't require IDs to be prefixed then anything that is linkable/referencable needs to have a unique ID. That's all I was saying above. It's a concern if we think there are likely to be conflicts. I don't get the sense that that's likely, though.

> My sense is that it's not a good idea to have the build process alter ids (at either the definition point or reference points). If nothing else, it could result in strange error messages.

Yeah I agree with this.

>  In the second para, there are mentions of String.prototype.normalize and String.prototype.localeCompare, each followed by a cross-ref to the corresponding subclause.

I would consider all of those links to be cross-refs (first with a custom title, second with a sec ID). I agree that the latter is not really required if the first is present.

I think the question raised in this thread is actually whether we want to encourage authors to use a convention where ID's for clauses are prefixed with "sec-". My sense is that this isn't required so I'd rather not encourage it as it adds more noise/typing.

In any case I think I can generate xrefs to all sorts of things with the current scheme - emu-xref href="#fig-1" and "#table-1" can do the right thing assuming these are declared with an id, for example. Probably will require wrapping both figures and tables in `<figure>`.

**Comment by bterlson** [comment]
You can now xref a clause or production by id and an abstract op by aoid in 2.0.0-beta1. Once figures, tables, and etc. are added you will be able to link to those by id as well.
