### ISSUE TITLE
Stop abusing <link rel="import" ...>

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#25]
As discussed recently in the web components spec repo, HTML imports are not the same as HTML includes. But Ecmarkup uses them as the latter.

I'd suggest instead introducing an `<emu-include href="...">` element. I'd further suggest that the post-processed version not be a simple replacement, but instead nest all the appropriate child content underneath the `<emu-include>` node. This latter because it's more like what would actually happen with a custom element, I think.

**Comment by bterlson** [comment]
The reason we went with the "abuse" route (specifically you and I, if you recall the conversation from months ago) was that import is a void element and so is much more terse. But if there's a good reason to move away I'm fine doing so.

**Comment by domenic** [comment]
Sorry, didn't mean to be accusatory :). Yeah, I definitely misunderstood imports at the time...

**Comment by bterlson** [comment]
I didn't mean it as such! No worries.

is there a strong reason to move away other than the bad feeling?

**Comment by domenic** [comment]
Not really; I just recently became cognizant that we were using a standard HTML tag but with nonstandard meaning.

**Comment by bterlson** [comment]
Yeah, I still feel bad about that. But void elements are so nice...

**Comment by bterlson** [comment]
So this is a standard HTML element used in standard ways with an additional layer of processing on top. It seems morally equivalent to giving special meaning to any other tag (like h1 means you get a secnum and other things). I think I'm going to close this for now. Can reopen if the abuse causes legitimate harm.

**Comment by domenic** [comment]
It is not used in standard ways, though. If we are rebuilding other random elements, img src is just as good and shorter (and morally equivalent).

**Comment by bterlson** [comment]
I don't think img is as moral because the src has to be an image file. With imports, you're linking to an html file (a semantically proper operation). The emu build tool inlines the import content. A custom elements implementation could do the same. This is not true with img afaict.

**Comment by domenic** [comment]
A custom elements implementation could not do the same, since link is not a custom element. Also, it's not semantically proper to locate links outside head. The mismatch is pretty stark.

**Comment by bterlson** [comment]
> A custom elements implementation could not do the same, since link is not a custom element.

Yes, I mean that you could write browser code to process the import (by prodding at its .import property, so no xhr even!) which is not true for images.

>  Also, it's not semantically proper to locate links outside head.

Be that as it may, links are everywhere outside of head on the web and all UAs handle it without issue as far as I know. Consider it Annex B behavior, which as @Domenic says, is part of the language whether you like it or not ;)

**Comment by domenic** [comment]
Sure,  if you modify the behavior of the browser, you can do anything. 

Anyway,  HTML imports are probably not going to be standardized. Perhaps as a compromise, pick another nonstandard rel, like include?

**Comment by domenic** [comment]
We were talking about semantics BTW, not what was allowed.
