### ISSUE TITLE
what kind of ecmarkdown is allowed?

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#29]
Now that ecmarkdown has a grammar, ecmarkup's README.md should be clearer about what kind of ecmarkdown content is allowed/reasonable in ecmarkup elements.

For instance, ecmarkdown says:
> Ecmarkup has an `<emu-alg>` element within which Ecmarkdown numeric lists can be used

which suggests that the content of an `<emu-alg>` is parsed as an ecmarkdown `OrderedList`. Is that the case?

Presumably the content of `<emu-{intro,clause,annex,note}>` is parsed as a `Document`. (In which case, is there much need for `<emu-alg>`?)

Then there are the "smaller" elements, like `<emu-xref>`, `<h1>`, and `<td>`. Is their content submitted *as such* to ecmarkdown, or are such elements (angle brackets and all) just part of a bigger submission? E.g., if I write

    <emu-clause id="test">
      <h1>The `this` keyword</h1>

      See <emu-xref href="#foo">the `that` keyword</emu-xref>, please.
    </emu-clause>

then is

      <h1>The `this` keyword</h1>

      See <emu-xref href="#foo">the `that` keyword</emu-xref>, please.

parsed (all at once) as an ecmarkdown `Document`? (Relying on the fact that the HTML tags will simply pass through unchanged.) As opposed to separate invocations for just the text content:

    "\n      "

    "The `this` keyword"

    "\n\n      See "

    "the `that` keyword"

    ", please.\n    "

**Comment by bterlson** [comment]
Presently, all text nodes under emu-clause (with the exceptions noted in the docs) are emd fragments. Emu-alg is an emd document.

Right now EMD doesn't support processing entire HTML documents very well. There are a number of cases to handle including but not limited to:

* Some HTML elements contain Paragraphs, eg. p, div, emu-clause, etc.
* Headers (and maybe others) shouldn't be wrapped in <p> tags at all.
* HTML elements interleaved with emu elements should be handled properly (eg. `*foo <b>bar*</b>`) where properly is yet to be defined :)

In this world you could argue emu-alg isn't required but it still is because emu-alg has some special processing like auto-linking abstract operations and probably also styles specific to algorithms as opposed to vanilla (un)?ordered lists.

**Comment by jmdyck** [comment]
[I think GFM ate some tags in your second bullet.]

> Presently, all text nodes under emu-clause (with the exceptions noted in the docs) are emd fragments.

Ah, so it *is* "separate invocations for just the text content".

> Emu-alg is an emd document.

So I could put multiple paragraphs within an emu-alg? There wouldn't even need to be an OrderedList? Is that seen as desirable, or just the way it currently happens to work?

> Right now EMD doesn't support processing entire HTML documents very well.

(Which is my current use case.)

> There are a number of cases to handle including but not limited to:
> 
>     HTML elements interleaved with emu elements should be handled properly (eg. *foo <b>bar*</b>) where properly is yet to be defined :)

I'd say that that's an ecmarkdown syntax error, as angle brackets shouldn't be allowed in a StarFormat. Ditto Underscore-, Tilde-, and Pipe-Formats. TickFormat is another matter, as you might reasonably want to write something like:

     The expression `3 > 2` yields the Boolean value *true*.

Except that in an HTML document, the '>' would necessarily be escaped. So I think it's okay to disallow angle-brackets in every Format.

> In this world you could argue emu-alg isn't required but it still is because emu-alg has some special processing like auto-linking abstract operations

In the ES6 HTML spec, abstract operations are auto-linked everywhere, so I assumed it wasn't a special property of emu-alg.

> and probably also styles specific to algorithms as opposed to vanilla (un)?ordered lists.

Yup, that could be.

**Comment by bterlson** [comment]
> So I could put multiple paragraphs within an emu-alg? There wouldn't even need to be an OrderedList? Is that seen as desirable, or just the way it currently happens to work?

Just happens to work that way.

Not allowing nesting of tags inside Formats seems like it would simplify some aspects of running emd on an entire html document.

**Comment by jmdyck** [comment]
The point of the issue was that the documentation should be clearer on this point, and I believe that's still the case. (If it makes a difference, when I said README.md, I meant spec/index.html.)

**Comment by bterlson** [comment]
I guess I forgot to push the commit. Will do so today/tomorrow.
