### ISSUE TITLE
Formatting nits

### ISSUE THREAD

**Issue by bterlson** [bterlson/ecmarkup#30]
As reported by Domenic in tc39/ecmascript-asyncawait#59:

* [x] Add styling for emu-const
* [x] Remove emu-t right margin when inside normal text.
* [x] Make Completion auto-link appropriately.

**Comment by ljharb** [comment]
It seems like v1.7.0 also no longer includes newlines in the generated HTML between steps in `emu-alg` blocks - is this related, or should it be a separate issue?

**Comment by bterlson** [comment]
@ljharb That was as a result of removing the beautify step from EMD so if the line breaks important to you, file a bug there!

**Comment by ljharb** [comment]
It looks like the issue was decided in https://github.com/domenic/ecmarkdown/issues/12 - I'm not sure why this particular formatting would be that slow.

**Comment by domenic** [comment]
If you want to beautify, beautify the whole document as a post-processing step. Don't build that into the tools.

**Comment by ljharb** [comment]
Do you have a recommended tool to use? Typically I've found it easiest to beautify during generation of HTML, but super difficult to do reliably after.

**Comment by domenic** [comment]
Well, we were already doing it after the generation of the HTML, so you're not going to get anything different. js-beautify is what I used.

**Comment by ljharb** [comment]
Sounds good, I'll try that, thanks.

**Comment by bterlson** [comment]
Not special-casing Completion - Completion{ ... } will link to the term Completion, which seems fine. Just need Completion to have a dfn in the source doc so it ends up in the biblio. See https://github.com/jmdyck/es-spec-emu/issues/6.

**Comment by bterlson** [comment]
These are all addressed in 2.0.0-beta1
