### ISSUE TITLE
aoid for emu-alg?

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#33]
I was wondering why the 'aoid' attribute was allowed on both emu-clause and emu-alg. Was there a particular situation you had in mind where you'd want to link to an emu-alg rather than an emu-clause?

(Also, in the description for emu-alg, it says "A unique name identifying this clause", but "clause" should presumably be "algorithm" or "element".)

**Comment by domenic** [comment]
+1, this is confusing and has caused confusion in 402. emu-clause only would be nicer.

**Comment by bterlson** [comment]
To support multiple algs per clause, mostly. See this intl section: only the second emu-alg defines an abstract operation: https://tc39.github.io/ecma402/#sec-datetime-format-functions.

**Comment by domenic** [comment]
So for example I think either that clause needs to contain FormatDateTime and ToLocalTime subclauses, or we need to mark those up as `When the <dfn aoid="FormatDateTime">FormatDateTime</dfn> abstract operation is called`...

**Comment by jmdyck** [comment]
> See this intl section: only the second emu-alg defines an abstract operation

Ah, yes. ES5 had cases like this, but then (pretty much) every abstract operation got its own clause in ES6. I didn't realize that Intl hadn't followed suit.

**Comment by bterlson** [comment]
Removed aoid from emu-alg. Domenic's approach will be required (though is presently not yet implemented).
