### ISSUE TITLE
generalizing aoid

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#34]
There are clauses that define *multiple* abstract operations, which the 'aoid' attribute doesn't (appear to) allow for. E.g. 20.3.1.2 "Day Number and Time within Day" defines `Day(t)` and `TimeWithinDay(t)`, and the HTML ES6 spec links uses of those abstract operations back to that clause.

Moreover, that clause also defines `msPerDay`, which is a 'spec constant', not an abstract operation, but the HTML also links uses of that constant back to that clause.

Even more generally, the HTML also links certain phrases like "bound function" and "internal slot".

So I'm thinking it might be useful to generalize the 'aoid' attribute into something that gives a list of all the things (operations, constants, phrases, whatever) defined by an emu-clause. (Or at least, all the things whose uses should be auto-linked back to that section.)

**Comment by domenic** [comment]
I'd rather link directly to the thing being described, than to the containing clause. The exact scheme for this isn't exactly clear though. `<dfn id="">` and maintain an appropriate database?

**Comment by bterlson** [comment]
so aoid can be attached to an emu-alg element which seems sufficient to describe all the algorithm-like things including multiple algorithms defined per-clause (in such cases you probably want to link directly to the algorithm anyway). Algorithm-like things are only auto-linked when called (eg followed by a paren) in an algorithm. For cases where a clause's only purpose is to define an algorithm (the vast majority) I think linking to the clause is right.

Phrases like "bound function" and "internal slot" seem separate from abstract operation IDs. I believe these should be tracked separately in the biblio file. Unsure how to mark them up but will think about it. I like using <dfn> for the purpose though.

**Comment by domenic** [comment]
> including multiple algorithms defined per-clause (in such cases you probably want to link directly to the algorithm anyway). 

I don't quite agree. I really prefer to be linked not directly to the steps, but to some kind of header or dfn which includes the actual name of the algorithm.

**Comment by bterlson** [comment]
I agree, with the additional qualification that it should link to a header and that header should be a clause :-P It seems like we're considering the behavior of something that isn't a best practice (and not very common anyway).

**Comment by domenic** [comment]
Possibly true. Either way, I'd like to disallow aoid on emu-alg because it encourages the bad practice of linking directly to algorithm steps. We should either lift everything to a clause or find a better solution.

**Comment by jmdyck** [comment]
> so aoid can be attached to an emu-alg element which seems sufficient to describe all the algorithm-like things including multiple algorithms defined per-clause

Well, except that, e.g., `Day(t)` and `TimeWithinDay(t)` are defined by equations, not a series of steps, so it seems incorrect to put them in emu-algs. (In es-spec.emu, they're each in a `<div class=display">`. (This happens a fair bit in 20.3 "Date Objects".)

> Algorithm-like things are only auto-linked when called (eg followed by a paren) in an algorithm.

Presumably you're talking about the current behavior of ecmarkup, but I'll point out that it's not true of the HTML ES6 spec. E.g., if you search for "ValidateTypedArray", the first occurrence is outside an algorithm, but is auto-linked to the definition.

> For cases where a clause's only purpose is to define an algorithm (the vast majority) I think linking to the clause is right.

Agreed, so that (on arriving there) you don't have to scroll back to see the operation name, its parameter list, and its preamble.

> Phrases like "bound function" and "internal slot" seem separate from abstract operation IDs.

That's how it seemed to me too, but in reconstructing the HTML ES6 spec from es-spec.emu, I wound up treating them the same.

> I believe these should be tracked separately in the biblio file. Unsure how to mark them up but will think about it. I like using for the purpose though.

Was there a tag between "using" and "for" that GFM ate?

**Comment by bterlson** [comment]
> Was there a tag between "using" and "for" that GFM ate?

Yes :( Edited. It was \<dfn>

> Presumably you're talking about the current behavior of ecmarkup

Yes, definitely :)

> E.g., if you search for "ValidateTypedArray", the first occurrence is outside an algorithm, but is auto-linked to the definition.

All occurances of ValidateTypedArray in algorithms use the call form. But yes, we probably want auto-linking outside of algorithms - this is I suppose true for any abstract operation.

We have two questions, though:

1. Is 'bound function' and etc. an aoid or something else. If something else, how do you define it?
2. how do we auto-link to aoids in body text

For 1 I say it's something else - let's call it a phrase. All aoids are phrases as well. All occurrences of a phrase are auto-linked. You define a phrase by wrapping it in a \<dfn> element (or define an aoid on a clause).

For 2, I'm not sure how to do. It doesn't seem like a good choice to search the entire document for every phrase (will be ~100 of them) but the only alternative I can think of is requiring markup. Maybe we continue auto-linking function calls as now and require \<emu-xref> to crease a phrase you want to link to its definition. Thoughts?

**Comment by domenic** [comment]
I think searching the entire document would be best from author convenience. Alternately you could put the burden on authors with lightweight `Stuff stuff [bound function] stuff stuff`, but it seems too easy to forget to bracket your phrases unless you keep a mental list of all phrases ever.

**Comment by bterlson** [comment]
Maybe I should experiment but I get the feeling that searching the entire ES6 spec for 100+ phrases is going to be slow. Maybe not though.

**Comment by domenic** [comment]
I mean there's certainly slow ways to do it (doing repeated indexOf searches 100 times) but a well-coded algorithm and data structure could do it in one pass.

**Comment by jmdyck** [comment]
> Is 'bound function' and etc. an aoid or something else.
> If something else, how do you define it?
> 
> I say it's something else - let's call it a phrase. All aoids are phrases as well. All occurrences of a phrase are ideally auto-linked. You define a phrase by wrapping it in a <dfn> element (or define an aoid on a clause).

Makes sense to me.

One thing I left out of my original comment was that, ideally, it would be possible for software to easily infer all the auto-linkable phrases that a clause defines, by simple inspection of the content of the clause. So, as long as an author had correctly marked up their content, they wouldn't need to remember to create/update an 'aoid' attribute (or similar) in the clause-header.

But the ES6 spec is a little far from this ideal, so I basically had to make ad hoc lists of the not-easily-inferable phrases defined by clauses, in order to reconstruct its auto-linking.

> how do we auto-link to aoids in body text
> 
> I'm not sure how to do. It doesn't seem like a good choice to search the entire document for every phrase (will be ~100 of them) but the only alternative I can think of is requiring markup. Maybe we continue auto-linking function calls as now and require <emu-xref> to crease a phrase you want to link to its definition. Thoughts?

What I ended up doing in emu_to_html.py was:
- construct a (rather large) regular expression that would match any of the defined phrases
- compile it once, then
- run it (almost) everywhere.

I think it might have been fairly quick if it could have run on the text of the whole document, but I had to run it on the text of every little text node, which probably slowed things down. One trick though: put the phrases in descending order of length before you put them in the regex, to avoid problems when one phrase is a substring of another (e.g., "Module Record" and "Source Text Module Record").

**Comment by bterlson** [comment]
I was planning on using your scheme, actually, it's basically how my original emd lexer worked (good tip on the order of text length :-P). Right now running on a per-text-node basis I think is the right approach. But since the regexp only needs to be constructed once I think this should only have as much overhead as a full DOM walk (and may actually save some scan time as a result of skipping tags and comments and such?)

**Comment by jmdyck** [comment]
> Right now running on a per-text-node basis I think is the right approach.

Yeah, you pretty much have to, otherwise it's hard to:
- suppress all auto-linking from certain elements like 'h1' and 'dfn'; and
- suppress auto-linking for a phrase within the clause where it's defined.

**Comment by bterlson** [comment]
Dfn-based auto-linking is in 2.0.0-beta1
