### ISSUE TITLE
equational definitions

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#35]
Within 20.3.1 ("Overview of Date Objects and Definitions of Abstract Operations"), many of the abstract operations are defined, not with a series of algorithmic steps, but with an equation (single-line or multi-line). For example, see 20.3.1.3 ("Year Number"): http://www.ecma-international.org/ecma-262/6.0/#sec-year-number

Should ecmarkup have a particular way to mark these up? E.g. something analogous to emu-alg:
```
    <emu-eqn>
        DaysInYear(_y_)
            = 365 if (_y_ modulo 4) != 0
            = 366 if ...
            ...
    </emu-eqn>
```

(Currently, over at es-spec-emu, such definitions mostly just inherit the markup they have in the HTML ES6 spec: `<p class="normalBullet">DaysInYear(_y_) <br> = 365 if (_y_ modulo 4) &ne; 0 <br> ...</p>`)

**Comment by bterlson** [comment]
Do you envision any special behaviors for emu-eqn? I guess they can hold an aoid?

**Comment by jmdyck** [comment]
Yes, it would normally have an aoid, and also it would treat its content specially (similar to an emd List).

**Comment by bterlson** [comment]
Do you mean the insides are parsed in some intelligent way? Or specially in that some things auto-link while some don't? I'm just trying to get a handle on how `<emu-eqn>` would be implemented. I suppose we could make it like a "pre" element so whitespace is respected, and then follow `emu-alg` by allowing auto-linking of phrases and calls to aoids. Anything else required?

**Comment by domenic** [comment]
Here's a potentially-radical suggestion: what if we had `<emu-eqn>`'s insides be parsed as LaTeX (using compile-time Mathjax)?

Probably too heavy-weight given how few of these there are and how little math they use, but it does seem like we're heading down the route of inventing some new micro-language...

**Comment by bterlson** [comment]
That's radical and really cool, but I'm not sure we can justify it if all we need is pre formatting and some autolinks...

**Comment by jmdyck** [comment]
> Do you mean the insides are parsed in some intelligent way?

'Intelligent' to the extent that (as when processing an emd list) newlines are significant: a line whose first non-whitespace char is '=' is (the start of) one of the 'pieces' in a piecewise equational definition. (Or you could require exactly one line per 'piece', so that every line after the first is a 'piece', regardless of what its first non-whitespace character is. But then that's less like an emd list.)

> Or specially in that some things auto-link while some don't?

I was thinking that you'd get the same auto-linking as if the content were in an `<emu-alg>` or `<p>` or `<li>`, say.

**Comment by bterlson** [comment]
Do you not like the approach I outlined above - pre formatting and emu-alg-style autolinks? Doing any more detailed parsing of emu-eqn feels like a waste.

**Comment by jmdyck** [comment]
Depends what you mean by "pre formatting". If you mean that an `<emu-eqn>` would be converted into a `<pre>`, then I don't like that it would (with normal styling) be rendered in a monospace font. On the other hand, if you mean that it would convert to an element (say, `<p class="emu-eqn">`) whose associated style includes `white-space: pre`, then that could be okay. Actually, I think something like
```
p.emu-eqn {
    white-space: pre-line;
    margin-left: 4em;
    text-indent: -2em;
}
```
would be even better, since then you get consistent indenting in the rendering, regardless of the indenting in the source.

As for " emu-alg-style autolinks": I guess so... are autolinks inside an emu-alg different from autolinks outside?

And I'm assuming the content would be treated as an ecmarkdown fragment.

**Comment by bterlson** [comment]
> As for " emu-alg-style autolinks": I guess so... are autolinks inside an emu-alg different from autolinks outside?

Inside emu-alg abstract ops are only linked when followed by a paren. Perhaps needlessly.

**Comment by jmdyck** [comment]
The other thing that's special about (some) equational definitions in the ES6 *PDF* is vertical alignment: in 20.3.1.4 "Month Number" and in 20.3.1.5 "Date Number", all the "if"s are vertically aligned, and in 20.3.1.11 "Hours, Minutes, Second, and Milliseconds", all the equal signs are vertically aligned.

So *if* you wanted to reproduce that appearance, it might require special processing of `<emu-eqn>` content.

On the other hand, the ES6 *HTML* doesn't preserve those alignments, and it doesn't look terrible.

(So, probably not worth the bother at this point, but I figured I should mention it.)

**Comment by bterlson** [comment]
Yeah I say ignore that alignment of ifs. Looks nice but strictly not necessary.

Question: why do we want aoid on emu-eqn? Do we want to encourage people to define aoid on the parent clause and only have one eqn per clause? Maybe the fact that ES6 doesn't conform to this guideline at all is reason enough to allow it for now?

**Comment by bterlson** [comment]
Also, bad news WRT white-space: pre/white-space: pre-line - either of these will prevent text-indent from working. Additionally neither plays well with the ::first-line selector. Unless someone knows something clever we'll have to do processing (perhaps simply wrapping each line in <emu-eqn-line> elements (or something else if there is a reasonably semantic alternative).

**Comment by jmdyck** [comment]
> Question: why do we want aoid on emu-eqn?

Well, over at es-spec-emu, I want it so that I can (in a non-ad-hoc way) set up auto-linking for terms defined via `<emu-eqn>`.

> Do we want to encourage people to define aoid on the parent clause and only have one eqn per clause?

Maybe. Though I don't think, e.g. [20.3.1.2](http://www.ecma-international.org/ecma-262/6.0/#sec-day-number-and-time-within-day) would be as readable if it were split into three clauses.

**Comment by bterlson** [comment]
Makes sense.

Also, forget emu-eqn-line. Div works fine :)

**Comment by bterlson** [comment]
Added in 2.0.0-beta2.

**Comment by jmdyck** [comment]
> Also, forget emu-eqn-line.

Not sure what you mean there. Is that an allusion to "perhaps simply wrapping each line in elements"?

**Comment by jmdyck** [comment]
> white-space: pre/white-space: pre-line - either of these will prevent text-indent from working. Additionally neither plays well with the ::first-line selector.

They all appear to co-exist okay in Firefox and Chromium and Opera.

E.g., when styling the .emu document,
```
emu-eqn {
	display: block;
	margin-left: 4em;
	text-indent: -2em;
	white-space: pre-line;
}

emu-eqn:first-line {
	color: red;
}
```
works as advertised. (And similarly if the `<emu-eqn>` are converted into `<p class="emu-eqn">`.)

**Comment by bterlson** [comment]
[This](http://codepen.io/anon/pen/RPmdQe) doesn't work in any browser for me. What am I missing?

**Comment by jmdyck** [comment]
Ah. With `white-space: pre-line` (or `pre-wrap` or `pre`), the "first line" (for the purposes of both `text-indent` and `:first-line`) is from the end of the start tag to the first linebreak, which in that example is an empty line. So to get the desired effect, you have to change
```
<emu-eqn>
DaysInYear(y) 
  = 365 if (y modulo 4) ≠ 0
```
to
```
<emu-eqn>DaysInYear(y) 
  = 365 if (y modulo 4) ≠ 0
```

(This is unlike HTML's `<pre>` element, which strips a leading newline.)

**Comment by bterlson** [comment]
Ahh yes. Hmm, guess I can just trim the starting whitespace then.

**Comment by bterlson** [comment]
On second thought, trimming whitespace is a bad idea as beautification will change how it renders. I am going to keep the div wrapping approach...

**Comment by jmdyck** [comment]
You can't tell beautification where not to insert linebreaks?

**Comment by bterlson** [comment]
Some you can, some you can't, I imagine. Anyway we don't want people to have to configure their beautifiers IMO.
