### ISSUE TITLE
Linkify `Type(x)`

### ISSUE THREAD

**Issue by ljharb** [bterlson/ecmarkup#36]
In the spec, when `Type(x)` appears, "Type" links to http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-data-types-and-values. Can `ecmarkup` link that too?

**Comment by bterlson** [comment]
Type now auto-links with the updated biblio in 2.0.0-beta2 (see release notes for instructions on installing).

**Comment by ljharb** [comment]
Thanks!
