### ISSUE TITLE
Blank line leads to blank section

### ISSUE THREAD

**Issue by littledan** [bterlson/ecmarkup#39]
Let's continue the discussion from https://github.com/domenic/ecmarkdown/issues/38

```
<emu-clause>
<h1>Foobar</h1>

Baz
</emu-clause>
```

The result has an empty body and just a heading.

**Comment by littledan** [comment]
And this was done with ecmarkup v2.0.3

**Comment by bterlson** [comment]
I guess this is a dupe of #40 actually.

**Comment by domenic** [comment]
Is it? What I got from this bug report was that the text "Baz" actually disappeared. Which seems bad.

**Comment by littledan** [comment]
Yeah this is a different bug

**Comment by bterlson** [comment]
Oh, sorry! I misread the issue :(

**Comment by bterlson** [comment]
Tracked it down, made multiple fixes to EMD in this area: https://github.com/domenic/ecmarkdown/pull/39.

**Comment by bterlson** [comment]
This is fixed in the latest EMD!
