### ISSUE TITLE
emu-table caption in attribute: what about markup?

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#41]
Putting an emu-table's caption in an attribute (as opposed to a child element) complicates the story if there's markup in the caption. E.g., in ES6:
- Table 49 --The _TypedArray_ Constructors
- Table 52 -- _Iterable_ Interface Required Properties
- Table 53, 54, 55 -- similarly

(The same goes for markup in the caption of an emu-figure or emu-example, but ES6 doesn't have any examples of that.)

**Comment by bterlson** [comment]
Probably markup is the right choice. <emu-caption> or <figcaption>?

**Comment by bterlson** [comment]
Guess emu-caption is the only choice here considering that figcaption is only semantically valid inside a figure (and things with an emu-caption might compile to asides or other things maybe).

**Comment by bterlson** [comment]
This is implemented now.
