### ISSUE TITLE
Add watch mode

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#42]
@littledan mentioned this today and it's a great idea.

One benefit is that if you don't shut down the process, you can avoid the jsdom-require startup costs.

Here's a quick start; needs some hacking to remove the bikeshed stuff. https://github.com/whatwg/streams/blob/master/local-watch.js

Optional cool feature: insert live reload script tag and use websockets to communicate with it. I understand this is pretty easy to drop in these days.

**Comment by jmdyck** [comment]
(What is watch mode?)

**Comment by bterlson** [comment]
@jmdyck watch mode lets you kick off your build process whenever your files change on disk. This would let us avoid some startup/teardown work (especially jsdom require time which is ~1s on my laptop).

Yes, this is fairly easy with fs.watch. Should be no problem.

Live reloading is also possible and easy. What I really want, though, is incremental build. When working on a document the size of ES6 it will be very handy to be able to build only a single import and update it in the document (this was one reason I switched to \<emu-import> - it makes this process easier!)

**Comment by bterlson** [comment]
Added watch mode in 2.1 (https://github.com/bterlson/ecmarkup/releases/tag/2.1.0)

**Comment by domenic** [comment]
Hmm why `ecmarkup --watch` instead of `ecmarkup watch`? Feels more like a sub-command than a flag.

Ah well, probably too late to change it now.

**Comment by bterlson** [comment]
I'm not sure I understand what makes a thing be subcommandy vs. flagy. Thoughts?

**Comment by domenic** [comment]
It feels like a different mode of the program, instead of a boolean parameter you pass to the existing program. Trying to think of other examples besides watch subcommands...  I guess a lot of them are in programs like git where there is no main command, so maybe my intuition is off.
