### ISSUE TITLE
Tilde-marked-up word at start of line must be preceded by space at end of previous line, or word will run together with next word

### ISSUE THREAD

**Issue by lars-t-hansen** [bterlson/ecmarkup#43]
For example, consider a paragraph:
```
  blah blah blah
  ~Atomics~ foo bar baz
```
There is no space at the end of the first line (though there are some spaces at the beginning of the second).  The markup will then be something like this:
```
blah blah blah<emu-const>Atomics</emu-const> foo bar baz
```
with a space missing before the emu-const markup.  Adding a space at the beginning of the first line fixes this but is unpleasant.

**Comment by domenic** [comment]
In general newlines should be turned into single spaces, I think. I guess this is an Ecmarkdown bug.

**Comment by bterlson** [comment]
I believe the ideal here is to preserve line breaks in the output and leave it to UAs to convert linebreaks to space. Looks like EMD is trimming trailing line breaks and whitespace: https://github.com/domenic/ecmarkdown/blob/master/lib/emitter.js#L32. Presumably that was added for a reason but I'm not sure what it is. Thoughts?

**Comment by bterlson** [comment]
Looking at the diff if I remove that line, I think this was a fix to get the starting and ending li on the same line after beautification. Without this line, most list items look like `<li>foo\n</li>`. Perhaps the best fix is to move the trim to the list item emitter here https://github.com/domenic/ecmarkdown/blob/master/lib/emitter.js#L27. All the tests pass except one that seems to highlight this bug, which seems encouraging.

**Comment by bterlson** [comment]
Fixed in the latest Emd!
