### ISSUE TITLE
Preserve / generate line breaks in output when sensible

### ISSUE THREAD

**Issue by lars-t-hansen** [bterlson/ecmarkup#44]
This came up in the context of issue #43, but I think it deserves its own ticket: Preserving more line breaks from the input in the output would be helpful, as it makes diffing the output with its previous version(s) more meaningful.  As it is, when I have a bulleted list (say) it is run together as one very long line in the output, making it effectively meaningless to "git diff" it.

On a closely related note, the markup that is generated for the TOC should have meaningful line breaks, for the same reason.

**Comment by domenic** [comment]
I think we've made the conscious decision that the build tool output is not supposed to be useful or meaningful.

If you'd like pretty output, we suggest you run a HTML beautifier on the output afterward.

**Comment by bterlson** [comment]
A post-build beautification step is the way to go. @ljharb does this, see an example package.json file here: https://github.com/ljharb/String.prototype.matchAll/blob/master/package.json#L7. Hopefully this will work for you?

It would be a lot of work to make the generated TOC and other generated content have linebreaks. Most of those elements are created with the DOM API (createElement/appendChild) so have no surrounding space. Perhaps I could find ways around this but I think beautification should work.

**Comment by ljharb** [comment]
I very much prefer when tools have a single responsibility - as long as the output `ecmarkup` produces is capable of being beautified/processed by another tool, I'm content with `ecmarkup` not concerning itself with it.

If at some point in the future, `ecmarkup` fails to be compatible with other tools, that's when I'd want `ecmarkup` to make whatever necessary changes to accommodate them.

**Comment by lars-t-hansen** [comment]
That's fine, a postprocessor is a totally adequate solution.  Thanks.
