### ISSUE TITLE
Table 3: star/emu-val vs. backtick/code

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#45]
In Table 3, the distinction between star/emu-val and backtick/code is unclear. E.g., given the example of putting 'Function.prototype' in backticks, it seems like it would also be reasonable to put 'TypeError' in backticks, but we have the example of putting 'TypeError' in stars. Are they both valid, depending on context? If so, can you explain when one should use one vs. the other?

**Comment by jmdyck** [comment]
One thing that occurs to me: in the ES6 spec, most occurrences of 'TypeError' are in the context of "throw a TypeError exception" or something similar, and performing this action involves "a newly created TypeError object". Now, what this means is not entirely clear: it could mean "create an object using the constructor in the 'TypeError' property of the global object", but since that could change, I'm guessing it means "create an object using the %TypeError% intrinsic". If it *were* the former, then putting 'TypeError' in backtick/code would make sense, since the constructor used is the same as what you'd get if you wrote 'TypeError' in the script. But since it probably means the latter, then maybe putting 'TypeError' in star/emu-val is a way to help convey that.

(Still, it would be clearer to say "throw a %TypeError% exception", or at least add a sentence to http://www.ecma-international.org/ecma-262/6.0/#sec-throw-an-exception .)

**Comment by bterlson** [comment]
I think the rationale for *'s is that it's not referring to the expression "TypeError" but the instrinsic TypeError object. Many of the references to X.prototype include "expression" verbage like in clause 17 (http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-standard-built-in-objects) which definitely points towards backticks for that usage. Probably %TypeError% should also be star'd but it's unformatted currently. I agree with your proposed clarification.

**Comment by bterlson** [comment]
I'm not sure how to clarify this in Table 3 though. Thoughts?

**Comment by bterlson** [comment]
Closing for now as I think it's ok, but will take PRs/suggestions for better copy if someone has them later.
