### ISSUE TITLE
`&lt;!--` translates to <emu-t><!--</emu-t>

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#46]
[I'm not sure if this is an issue with ecmarkup or grammarkdown.]

From [ES6 B.1.3](http://www.ecma-international.org/ecma-262/6.0/#sec-html-like-comments), the production:
```
SingleLineHTMLOpenComment ::
  `&lt;!--` SingleLineCommentChars?
```
is translated into an `<emu-production>` containing:
```
<emu-t><!--</emu-t>
```
which opens up an HTML comment that swallows up the next few productions.

**Comment by bterlson** [comment]
Grammarkdown PR fixing this: https://github.com/rbuckton/grammarkdown/pull/13.

**Comment by bterlson** [comment]
This is fixed!
