### ISSUE TITLE
Documentation error when discussing non-terminal references?

### ISSUE THREAD

**Issue by impressivewebs** [bterlson/ecmarkup#56]
In the [editorial conventions](http://bterlson.github.io/ecmarkup/#editorial-conventions) section, in the last row of "Table 4: Inline styles/conventions", it describes "Non-terminal references" and defines the "Ecmarkup Functionality" as `<emu-xref id="#prod-FunctionExpression"></emu-xref>`. However, on the [Ecmarkdown readme](https://github.com/domenic/ecmarkdown#inline-formatting) it says that nonterminals are written as `|x|` and translate to `<emu-nt>x</emu-nt>`.

This looks like a contradiction to me. Is the 4th line of Table 4 incorrect in using `<emu-xref>` as the output? Or is there something I'm not understanding here?

**Comment by bterlson** [comment]
Ahh yes, this is a doc bug. Emd readme is correct (although I was planning on changing it to align with the Emu readme, this is harder than I expected and I may not do it now)
