### ISSUE TITLE
"metadata" blocks don't support leading tabs

### ISSUE THREAD

**Issue by ljharb** [bterlson/ecmarkup#57]
The following two blocks work fine:

```html
<pre class="metadata">
title: String.prototype.padLeft / padRight
stage: 1
contributors: Jordan Harband
</pre>
```
```html
<pre class="metadata">
  title: String.prototype.padLeft / padRight
  stage: 1
  contributors: Jordan Harband
</pre>
```

However, the following block, which is indented with `\t`:
```html
<pre class="metadata">
	title: String.prototype.padLeft / padRight
	stage: 1
	contributors: Jordan Harband
</pre>
```

prints the following warning:
`[2015-09-30T22:50:02.743Z] Warning: metadata block failed to parse [2015-09-30T22:50:02.749Z] Warning: Contributors not specified, skipping copyright boilerplate. Specify contributors in your frontmatter metadata.`

**Comment by domenic** [comment]
http://www.yaml.org/faq.html

**Comment by bterlson** [comment]
Spaces are the one true indent. So say we all.

**Comment by ljharb** [comment]
It's a `<pre>`, and there's no yaml label, and the error message doesn't mention yaml.

Perhaps `<script type="yaml">` would be better?

**Comment by bterlson** [comment]
Error message should say something about what it's attempting to parse, I agree.
