### ISSUE TITLE
having both <title> and "title:" metadata should error out

### ISSUE THREAD

**Issue by ljharb** [bterlson/ecmarkup#58]
Since it's redundant to specify both `<title>` and a metadata `title:`, when both are present, ecmarkup should ideally error out and instruct me to remove one.

Alternatively, it should stop supporting both, and force one method of specifying the title.

**Comment by bterlson** [comment]
I think I like the current behavior. You can specify a title in the metadata block and it will generate the header boilerplate, but if you wanted to you could override the document title.

**Comment by ljharb** [comment]
Fair - perhaps a warning if they're the same? No worries if you don't think that's valuable.
