### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by bterlson** [bterlson/ecmarkup#6]
Should highlight syntax inside pre tags based on a language attribute.

**Comment by domenic** [comment]
The [canonical HTML pattern for this](https://html.spec.whatwg.org/multipage/semantics.html#the-code-element) is `<pre><code class="language-pascal">...</code></pre>`.

**Comment by bterlson** [comment]
Alright, let's go with the canonical pattern then!

**Comment by bterlson** [comment]
Done, highlighting in <pre><code> blocks.
