### ISSUE TITLE
dependency on intl?

### ISSUE THREAD

**Issue by jmdyck** [bterlson/ecmarkup#61]
Given that lib/Spec.js refers to Intl, shouldn't ecmarkup have a dependency on intl?

**Comment by domenic** [comment]
Intl is built in to Node.js as a global, just like all other modern JS VMs

**Comment by bterlson** [comment]
I guess it probably came to node at v4.0, which is the lowest version of Node I intend to support.

**Comment by jmdyck** [comment]
I was acting on the fact that README.md says "Requires iojs, not Node.js."
It sounds like exactly the opposite is true now. Is that correct?

**Comment by bterlson** [comment]
io.js should work fine as well, but I've updated the readme to require Node 4.0 or above which is definitely more accurate.

**Comment by jmdyck** [comment]
> io.js should work fine as well

Depends on the version.
I was using io.js v3.0.0, which gave me "ReferenceError: Intl is not defined".
Looks like Intl was added in v3.1.0.
