### ISSUE TITLE
Link 11.6.2.1 Keywords to the implementation details in 12.9

### ISSUE THREAD

**Issue by camillobruni** [bterlson/ecmarkup#65]
We spent an infinite 360 seconds running through the spec to find the runtime semantics of the `in` operator – and no, grepping for "in" is definitely not an option here (19237 hits to be precise) ;). 
Of course now all the magic is gone and we know where to find section 12.9, but I think it would be awesome to link the keywords/operators from 11.6.2.1 to their detailed section for superior browsing quality.

**Comment by bterlson** [comment]
Sorry I missed this until just now!

This is more of a bug against the spec (tc39/ecma262). That said... the problem with linking is the keywords are used in multiple places. Eg. `in` could reasonably link to the for-in statement or the `in` operator.

But... it is basically impossible to find the `in` operator I agree. What will help substantially is having the grammar annex like the official spec. Much easier to scan to find its various usages there.

If you don't think the annex is sufficient feel free to open another issue against ecma262!
