### ISSUE TITLE
Would like autolinking for NextJob and the job names

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#67]
I would like every occurence of "NextJob _x_" in http://tc39.github.io/ecma262/ to link to http://tc39.github.io/ecma262/#sec-nextjob-result.

I would similarly like every occurrence of ScriptEvaluationJob (e.g. in http://tc39.github.io/ecma262/#sec-ecmascript-initialization 8.a.i.) to link to http://tc39.github.io/ecma262/#sec-scriptevaluationjob

I'm also unsure how this would even work but in http://tc39.github.io/ecma262/#sec-scriptevaluationjob it would be ideal if "ScriptEvaluation" in 4.b linked to http://tc39.github.io/ecma262/#sec-runtime-semantics-scriptevaluation. I realize this might be harder since in the general case Runtime Semantics are not unique... in this case they are though.

**Comment by bterlson** [comment]
I've made the necessary emu changes for this to work. Basically what I did was something I've been planning to do for a while - unify the handling of auto-linking across clauses and algorithms. Previously an operation would auto-link with just its name outside of algs (unless it was one of a set of "common" words like Type) but required parens inside of algs. Now the logic is the same everywhere - autolink just the abstract op name by itself unless its a common name, in which case it needs to be followed by a paren. This rule seems reasonable, and with it, MANY more things are auto-linking than before. Looks really nice, actually.

![image](https://cloud.githubusercontent.com/assets/11236/11701245/4fc461c2-9e83-11e5-8349-dbd233d5917f.png)
