### ISSUE TITLE
Shorthand for ReturnIfAbrupt

### ISSUE THREAD

**Issue by bterlson** [bterlson/ecmarkup#7]
Algorithm steps are littered with ReturnIfAbrupt calls. @wycats proposes a shorthand that could be compiled to ECMASpeak without too much difficulty: https://gist.github.com/wycats/1b829d55d1fdb97d8762.

**Comment by domenic** [comment]
I would rather just change ECMAspeak! Both the input and the output should contain this shorthand.

**Comment by bterlson** [comment]
I agree, although I suspect changes to ECMASpeak will take a while to happen...

**Comment by domenic** [comment]
Nah. Just write new specs using them. That's how they happen.

**Comment by domenic** [comment]
Cf. https://streams.spec.whatwg.org/#conventions

**Comment by bterlson** [comment]
Updating ECMASpeak is in progress: https://github.com/tc39/ecma262/pull/129.
