### ISSUE TITLE
missing git tags for releases beyond 3.0.0

### ISSUE THREAD

**Issue by michaelficarra** [bterlson/ecmarkup#86]
The latest git tag is `3.0.0`, but the latest release is `3.2.0`.

**Comment by bterlson** [comment]
Sorry my release discipline failed. I added release notes for 3.2.2 which summarizes everything since 3.0.

**Comment by michaelficarra** [comment]
@bterlson You should still tag the intermediate releases.

**Comment by bterlson** [comment]
I will if you can tell me how you use them!

**Comment by bterlson** [comment]
I added them for you. Still curious if you're using these somehow.

**Comment by michaelficarra** [comment]
@bterlson I just like to be able to do things like `git log 3.2.0...` or `git diff 3.1.0...3.2.0`.

**Comment by bterlson** [comment]
Makes sense, thanks :)
