### ISSUE TITLE
Do not autolink when already inside an `<a>` element

### ISSUE THREAD

**Issue by domenic** [bterlson/ecmarkup#88]
This would actually solve most of my over-agressive autolinking problems in https://streams.spec.whatwg.org/: both the TOC, and the messed up links to "ReadableStreamTee branch 1 cancel function" in https://streams.spec.whatwg.org/#readable-stream-tee.

**Comment by domenic** [comment]
Dang I didn't realize this would just require adding a tag to a list or I would have PRed it myself. Nice architecture!

**Comment by bterlson** [comment]
Haha, thanks. I've improved the factoring of the code quite a bit recently, although spec.js is still a disgusting monster.
